### ISSUE TITLE
Execution failed

### ISSUE THREAD

**Issue by evanthomas** [FarmBot-Labs/hello-farmware#1]
I was able to install this Farmware example through the web app but when I run it all I get is "Farmware execution failed". How do I debug this?

I should point out I don't actually have a Farmbot, just a pi3 running the OS at the moment.

**Comment by gabrielburnworth** [comment]
This Farmware is currently running successfully on the latest stable version of FarmBot OS, at least with an Arduino connected. Which FarmBot OS version are you using?

Connecting an FTDI cable to the Pi usually provides additional debug information.
